### ISSUE TITLE
Cannot hash builtin functions

### ISSUE THREAD

**Issue by astrojuanlu** [pycodehash/pycodehash#22]
```
In [5]: fh.hash_func(print)
...
    402 @property
    403 @utils.saveit
    404 def source_code(self):
--> 405     return self.pymodule.source_code

AttributeError: 'BuiltinModule' object has no attribute 'source_code'
```

**Comment by RUrlus** [comment]
@astrojuanlu Thanks for filling an issue. Builtin functions are not supported as they (often) do not have a python implementation we can look up. That said we should handle this exception and raise a better one.

**Comment by astrojuanlu** [comment]
Or instead of raising an exception, assume that builtin functions will never change? That way the user doesn't need to do a try-except to catch this special case and can pass _any_ function

**Comment by RUrlus** [comment]
We don't try to hash them when we encounter them as a call in a function body. This only happens when you explicitly hash an builtin. I am not sure what is more intuitive is this case. We could add an error option  to allow None/'' return instead of raising.
